print('init.lua ver 1.2')
wifi.setmode(wifi.STATION)
print('set mode=STATION (mode='..wifi.getmode()..')')
print('MAC: ',wifi.sta.getmac())
print('chip: ',node.chipid())
print('heap: ',node.heap())
print("waiting 8 seconds")
-- wifi config start
dofile("config.lua")
wifi.sta.connect()
tmr.alarm(0,8000,0, function()
								print("Startup")
								http = require("serviceHttp")
								telnet = require("serviceTelnet")
								func = require("buildinFunctions")
								func.autostart()
end)
